### ISSUE TITLE
When can we expect source code of the .NET SDK?

### ISSUE THREAD

**Issue by olegburov** [Azure/azure-cosmos-dotnet-v2#128]
The [Readme](https://github.com/Azure/azure-documentdb-dotnet/blob/master/sdk/Readme.md) file with a promise to open source the .NET SDK was published more than a year ago, and the source code is still not available.

Do you guys still plan to publish it?

**Comment by aliuy** [comment]
Yes - but we don't have any timelines yet. It turns this involves quite a bit of non-trivial work.

**Comment by sandorfr** [comment]
> It turns this involves quite a bit of non-trivial work.
I'm curious about that.

**Comment by aarondcoleman** [comment]
since incorporating DocumentDB and this SDK in to our codebase, we've hit a wall resulting from Issue #118 (we can't include a class library that has the SDK as a dependency as a dependency of our API app). One way I could have gotten around this was by having the source code to step through, and or, creating my own build. We're still without solution.

I'm not sure what's non-trivial about this (@aliuy) , but it seems imperative and probably a huge benefit to the DocumentDB product offering that the library source be opened. Would very much appreciate it.

**Comment by bpatra** [comment]
DocumentDB itself is already kind of a blackbox but when you add the SDK on top of it, troubleshooting becomes a nightmare. This is no mere issue you need to figure out something.

**Comment by bpatra** [comment]
Feature request asked on uservoice, consider upvoting
https://feedback.azure.com/forums/263030-documentdb/suggestions/18902368-opensource-documentdb-net-sdk

**Comment by Chappie72** [comment]
Hi DocumentDB team. Any update on the time lines for this?

**Comment by AlexPalma72** [comment]
Well looks like java is more trivial than c#, since the cosmosdb java sdk source code was open sourced. Dam the c# code is either a mess or is just easy to program in java.

**Comment by enricosada** [comment]
Ping. @ausfeldt
The original request is from 2016.
It's really difficult to help with this, if code is not opensource.

**Comment by manigandham** [comment]
There's a new version 3 of the .NET SDK for Cosmos DB now that's fully open source: https://github.com/Azure/azure-cosmos-dotnet-v3

**Comment by olegburov** [comment]
@manigandham is right. It's been already open source. Therefore, I'm closing this issue.
