### ISSUE TITLE
Linq expression produces large sql query

### ISSUE THREAD

**Issue by vaskravchuk** [Azure/azure-cosmos-dotnet-v2#425]
i have following linq query:
`.Where(e=>ids.Contains(e.id))`

where ids is IEnumerable<string> with list of rather big strings (ldap DN)
this linq expression produces sql which throws error:

`{"errors":[{"severity":"Error","location":{"start":0,"end":60787},"code":"SC3020","message":"The SQL query text exceeded the maximum limit of 30720 characters."}]}`

but when i write sql query manually and pass list of ids as parameter - everything works fine
`SELECT * FROM item WHERE ARRAY_CONTAINS(@ids, item.id)`

is it possible to reuse somehow parameter queries in linq expressions?

**Comment by kirankumarkolli** [comment]
@bchong95 please look into this

**Comment by kirankumarkolli** [comment]
@bchong95 please look into this

**Comment by bchong95** [comment]
You are seeing a common issue with sql query text hitting 30,720 character due to having an unbounded array of ids in the query. If you run .ToString() on the LINQ query you can see the sql query that is generated. Currently LINQ translates `.Where(e=>ids.Contains(e.id))` to an IN query instead of ARRAY_CONTAINS. The later can be parameterized while the prior can't be. 

To get around this you have to manually generate parameterized SQL queries:

https://azure.microsoft.com/en-us/blog/announcing-sql-parameterization-in-documentdb/

like you did in the second case, since the query text in that scenario is just 
```
"SELECT * FROM item WHERE ARRAY_CONTAINS(@ids, item.id)".Length
```

As opposed to the expanded list generated by in IN query. We are working on fixing this and it should come the next time we update the LINQ query translator.

Thank you.

**Comment by ryanoshag** [comment]
> We are working on fixing this and it should come the next time we update the LINQ query translator.

Any update on this?

**Comment by jakehockey10** [comment]
Still seems to be an issue for me.

**Comment by bchong95** [comment]
@khdang can you update on the above?

**Comment by khdang** [comment]
The parameterized query should and is going to have the same behavior with plain text query in the near future. Therefore, in general, we would recommend to break down the list into smaller lists if you hit the query length limit. Btw, the limit has been increased to 256Kb.

Nonetheless, V3 supports LINQ parameterized query. You can refer to this PR for more details: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/762. However, please keep in mind it's not the proper solution for this scenario as mentioned above.

**Comment by jakehockey10** [comment]
I appreciate the follow-up. My issue is that if I break up the list to avoid the too-long-of-a-query-string error, I cause myself to run into a request-rate-too-high-error.
