### ISSUE TITLE
Failed to acquire private key for emulator secrets certificate

### ISSUE THREAD

**Issue by krishnagupta21** [Azure/azure-cosmos-dotnet-v2#693]
**Describe the bug**
When I try to run `CosmosDB.Emulator.Exe` I get the following error:

`Failed to acquire private key for Emulator secrets certificate Error: 0x80090015`

I have tried uninstalling, deleting all files `AppData/Local/CosmosDbEmulator` and in `Program Files/Azure Cosmos Db Emulator` and reinstalling it. I have also tried `lodctr /r` multiple times. and also tried `CosmosDbEmulator /starttraces` before starting `CosmosDbEmulator`

**To Reproduce**
I uninstalled an old version and reinstalled the latest version (2.2.1-2).

**Expected behavior**
The emulator should start

**Environment summary**
SDK Version: 2.2.1
OS Version: Windows 10-64 bit

**Comment by krishnagupta21** [comment]
I was able to fix it by deleting all certificates (using Certificate Manager) related to DocumentDbEmulator and CosmosDbEmulator

**Comment by josh-yates** [comment]
Hi @krishnagupta21 -  I have run into the same issue as you. I followed your advice of deleting all certificates related to DocumentDbEmulator and CosmosDbEmulator and am now receiving
> Failed loading Emulator secrets certificate.
Did you encounter this? How did you go about deleting certificates?
Any advice you could give would be greatly appreciated - I've hit a brick wall here!
Thank you.

**Comment by DinoSourcesRex** [comment]
@josh-yates I know this is several years after the fact but for anyone who finds their way here if they encounter this the fix is relatively simple on Windows.

Press `Windows Key + R` and type in `certlm.msc` for the local certificates on the machine.

You will be looking at the "Friendly Name" column, the values you care about are the ones mentioned above - `CosmosDbEmulator` and `DocumentDbEmulator`.

# Option 1 - Find

Go to "Action > Find Certificates..." in the task bar on the certificate manager.

Search for `localhost` in the field `Issued By`. 

The list should contain the certs you care about.

# Option 2 - Manually search

Here you should look manually for the certificates that have the friendly names you care about. I found some in the following places, all issued to localhost.
* `Personal > Certificates`
* `Trusted Root Certification > Certificates`

Hope this helps someone.

**Comment by indupriya123** [comment]
@krishnagupta21 @DinoSourcesRex 

I still see this issue after deleting all the certs related to emulator. How to solve this?

![image](https://github.com/Azure/azure-cosmos-dotnet-v2/assets/29914414/a0518ff2-8ae4-4b57-ab7b-2f745656bc67)

**Comment by HermanCordes** [comment]
@indupriya123 @krishnagupta21 @DinoSourcesRex After following the walkthrough by @DinoSourcesRex, I'm running into the same issue as @indupriya123. Did anyone manage to resolve this issue?

I tried the obvious thing of removing the application and reinstalling, but that doesn't solve the issue and it also doesn't bring back the deleted certificates.

Curious to if someone found a definitive solution?

**Comment by vishesh147** [comment]
Years later, but I hope this is found by those who are looking for it. 

I found the root cause of Cosmos DB Emulator startup/certificate failures reporting:

```text
0x8009000F (NTE_EXISTS): Object already exists
```

In this case, `NTE_EXISTS` was misleading. Process Monitor showed the emulator first receiving `ACCESS DENIED` while reading existing private keys under:

```text
C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys
```

The affected key ACLs referenced an old per-session logon SID (`S-1-5-5-...`) instead of the user's permanent SID. The emulator apparently treated the inaccessible key as missing, tried to create it again, and then surfaced `NTE_EXISTS` because it already existed.

This explains why reinstalling the emulator, resetting its data, deleting certificates, and rerunning `/gencert` did not help: those actions do not repair persisted `MachineKeys` ACLs.

### Confirm


1. Run Procmon64.exe as Administrator.
2. Add filters:
```text
Process Name is Microsoft.Azure.Cosmos.Emulator.exe
Result is ACCESS DENIED
```
3. Start the Cosmos DB Emulator.
4. Look for paths containing  \Crypto\RSA\MachineKeys\



If it identifies specific files under `MachineKeys`, inspect their ACLs from elevated PowerShell:

```powershell
Get-Acl '<exact-path-from-Procmon>' |
    Format-List Owner, AccessToString, Sddl
```

### Fix

Run as Administrator and include **only** exact paths identified by Process Monitor:

```powershell
$keys = @(
    '<exact-MachineKeys-path-from-Procmon>'
)

$sid = [Security.Principal.WindowsIdentity]::GetCurrent().User
$rule = [Security.AccessControl.FileSystemAccessRule]::new(
    $sid, 'FullControl', 'Allow')

foreach ($key in $keys) {
    $acl = Get-Acl -LiteralPath $key
    $acl.SetAccessRule($rule)
    Set-Acl -LiteralPath $key -AclObject $acl
}
```

After repairing the affected key ACLs, the emulator successfully regenerated `CosmosEmulatorSecrets` and `DocumentDbEmulatorCertificate` and started normally.

Do **not** recursively modify or delete the entire `MachineKeys` directory; it contains private keys used by Windows and unrelated applications.
