### ISSUE TITLE
Unable to Serialize Subclasses of "Document"

### ISSUE THREAD

**Issue by robcthegeek** [Azure/azure-cosmos-dotnet-v2#7]
### Problem

I have a class that I want to store in Document DB. I subclassed this from `Document` because my Repository/Data Access layer cares about such things.

To be clear - it's something like:

``` csharp
public class MyDocument : Document {
    public string Custom { get; set; }
}

// After creating a document, I want to be able to do things like:
var doc = new MyDocument { Custom = "Something" };
var id = doc.Id;
var link = doc.SelfLink;
var custom = doc.Custom;
```

Within the code - all this appeared to be working fine, but when it came to serialization, my `Custom` property was being dropped.

I started to dig around and found that `Document` is a subclass of `JsonSerializable` - where there seems to be something amiss.

So - I got the code out to isolate it - the instance created from `FromObject` _looks_ OK (you can see the `Custom` property) - but when serialized, the information is lost.
**NOTE:** We know this isn't a problem with JSON.NET - that handles subclasses fine.

Observe - I created the following in [LINQpad](http://www.linqpad.net) (just add references to `Azure.Documents.Client` and `Newtonsoft.Json` and copy/paste):

``` csharp
void Main()
{
    var testDoc = new MyDocument {
        Custom = "Some Custom Property"
    };

    var test = FromObject(testDoc);
    test.Dump("Object Created from Document.FromObject - 'Custom' property visible:");
    JObject.FromObject(test).ToString().Dump("Serialized object - Y U NO SAVE?");
}

public class MyDocument : Document {
    public string Custom { get; set; }
}

internal static Document FromObject(object document) {
    if (document == null)
        return (Document) null;

    if (typeof (Document).IsAssignableFrom(document.GetType()))
        return (Document) document;

    JObject jobject = JObject.FromObject(document);
    Document document1 = new Document();
    // Private fields be damned!
    typeof(Document).GetField("propertyBag").SetValue(document1, jobject);
    // document1.propertyBag = jobject;
    return document1;
}
```

**SUGGEST:** I was really surprised to see this happening. Get `Document` to a POCO so we can subclass freely. It's serialization should be handled elsewhere.

**PS:** I'm not blocked - I can work around this.

**Comment by FelschR** [comment]
I have set JsonProperties on all my members that I want to serialize.
But I still had a strange issue that caused my objects to have BOTH instance members as well as dynamic(?) members under "Static members" -> "propertyBag" (seen in debugging mode).

The funny thing is when I change a property of one of those objects and serialize it the JSON will not have changed because it seems to retrieve the values from "propertyBag" which I can see hasn't changed.

It's extremely weird and I was working around it via some extra casting.
Now I noticed that when I changing my classes to use Resource instead of Document the "propertyBag" still existed but ONLY with fields like "_rid, etc. not my custom ones.
