### ISSUE TITLE
The cpu usage high when using documentdb client to query and update documents

### ISSUE THREAD

**Issue by luilucas** [Azure/azure-cosmos-dotnet-v2#706]
I used the v2.2.3 documentdb client in my business and found the usage of cpu is high when parallel fetching and replacing documents.

I read the source code, notice that the documentdb client use Newtonsoft.Json to serialize/de-serialize document, this two seemed to be cpu consumption operations. So, does it need to control the concurrent operations when querying/replacing the entire document?

And, will the serialization/de-serialization will be the bottleneck of concurrent tasks?

**Comment by j82w** [comment]
There has been a lot of improvements to address this in the [v3 SDK](https://github.com/Azure/azure-cosmos-dotnet-v2/issues/691) query pipeline. 

v3 SDK:
- Allows a custom serializer
- Only needs to deserialize the single property instead of the entire object for order by operations
- Exception-less pipeline
- Stream support

Concurrent tasks are restricted based on the query request options, and the size of the collection. The more RUs a collection has the more partitions it will contain thus allow more parallelism, but it's a double edged sword since now it needs to connect to twice as many machines. The serialization processes will probably be the most resource intensive operation. If you start maxing out the CPU on the machine it will start to impact the latency from the lack of CPU resources.

I would recommend looking at these links to help improve the query performance.
https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips
https://docs.microsoft.com/en-us/azure/cosmos-db/optimize-cost-queries
